name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install Git LFS
      - name: Install Git LFS
        run: |
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://bipinsaha:$HF@huggingface.co/spaces/bipinsaha/Docker_ClaiforniaHouse

      # Track large files with Git LFS
      - name: Track large files with Git LFS
        run: git lfs track "*.gz"   # Replace "*.your_extension" with the file extension(s) you want to track

      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: |
          git add .gitattributes
          git add .   # Add all changes including LFS-tracked files
          git commit -m "Enable Git LFS"
          git push --force https://bipinsaha:$HF@huggingface.co/spaces/bipinsaha/Docker_ClaiforniaHouse main
